/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 wagner.glb --transform 
Files: wagner.glb [813.99KB] > C:\Users\luisp\OneDrive\Ambiente de Trabalho\ProjFinal\trilhos-digitais\public\models\wagner\wagner-transformed.glb [52KB] (94%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/wagner/wagner-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube005.geometry} material={materials.PaletteMaterial001} scale={[0.689, 8.46, 8.46]} />
    </group>
  )
}

useGLTF.preload('models/wagner/wagner-transformed.glb')
