/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 wagner2.glb --transform 
Files: wagner2.glb [539.89MB] > C:\Users\luisp\OneDrive\Ambiente de Trabalho\ProjFinal\trilhos-digitais\public\models\wagner\wagner2-transformed.glb [8.11MB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/wagner/wagner2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube005.geometry} material={materials.PaletteMaterial001} scale={[0.689, 8.46, 8.46]} />
      <group position={[-4.895, -12.562, 0.034]} scale={1.826}>
        <mesh geometry={nodes.Layer_4mic_head_mesh.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Layer_4mic_head_mesh_1.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Layer_4mic_head_mesh_2.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Layer_4mic_head_mesh_3.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Layer_4mic_head_mesh_4.geometry} material={materials['Textura_1.002']} />
        <mesh geometry={nodes.Layer_4mic_head_mesh_5.geometry} material={materials['Textura_2.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/wagner/wagner2-transformed.glb')
