/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 wagner2.glb --transform 
Files: wagner2.glb [30.58MB] > C:\Users\luisp\OneDrive\Ambiente de Trabalho\ProjFinal\trilhos-digitais\public\models\wagner\wagner2-transformed.glb [795.4KB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/wagner/wagner2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -23.273, -8.897]} scale={[19.35, 4.588, 1.469]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Cube_5.geometry} material={materials['Textura_1.002']} />
        <mesh geometry={nodes.Cube_6.geometry} material={materials['Textura_2.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/wagner/wagner2-transformed.glb')
