/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 badge_bauhaus.glb --transform 
Files: badge_bauhaus.glb [292.46KB] > C:\Users\luisp\OneDrive\Ambiente de Trabalho\ProjFinal\trilhos-digitais\public\models\bauhaus\badge_bauhaus-transformed.glb [14.11KB] (95%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/bauhaus/badge_bauhaus-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[3.123, 1, 1.185]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[2.56, -0.327, -12.62]} rotation={[0, Math.PI / 2, 0]} scale={[0.367, 0.494, 0.336]} />
    </group>
  )
}

useGLTF.preload('/models/bauhaus/badge_bauhaus-transformed.glb')
