/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 prensa.glb --transform 
Files: prensa.glb [6.04MB] > C:\Users\luisp\OneDrive\Ambiente de Trabalho\ProjFinal\trilhos-digitais\public\models\prensa\prensa-transformed.glb [334.95KB] (94%)
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/prensa/prensa-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="untitled001"
          position={[0.073, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0.009]}
          scale={0.01}
        >
          <mesh
            name="s__1_001"
            geometry={nodes.s__1_001.geometry}
            material={
              materials[
                "Vintage_Newspaper_Print_Texture_Background_58059866_1.001"
              ]
            }
            position={[-404, 768, 1518]}
            scale={[9.674, 15.588, 0.229]}
          />
        </group>
        <mesh
          name="Object_2"
          geometry={nodes.Object_2.geometry}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <meshStandardMaterial color={"#6f4e37"} />
        </mesh>
        <mesh
          name="s001"
          geometry={nodes.s001.geometry}
          material={
            materials[
              "DD_Old_Paper_Texture_77722_DD_Old_Paper_Texture_77722.001"
            ]
          }
          position={[-4.043, 15.18, -7.692]}
          rotation={[-Math.PI / 2, 0, 0.009]}
          scale={[0.097, 0.156, 0.002]}
        />
        <mesh
          name="s__2_001"
          geometry={nodes.s__2_001.geometry}
          material={
            materials[
              "Vintage_Newspaper_Print_Texture_Background_58059866_1.001"
            ]
          }
          position={[-3.92, 14.01, 5.256]}
          rotation={[-Math.PI / 2, 0, 0.009]}
          scale={[0.063, 0.101, 0.001]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/prensa/prensa-transformed.glb");
