/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 prensa.glb --transform 
Files: prensa.glb [450.54KB] > C:\Users\luisp\OneDrive\Ambiente de Trabalho\ProjFinal\trilhos-digitais\public\models\prensa\prensa-transformed.glb [26.78KB] (94%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/prensa/prensa-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_0_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_0_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/prensa/prensa-transformed.glb')
