/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 wagnerAR.glb --transform 
Files: wagnerAR.glb [26.88MB] > C:\Users\luisp\OneDrive\Ambiente de Trabalho\ProjFinal\trilhos-digitais\public\models\wagnerAR\wagnerAR-transformed.glb [794.56KB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/wagnerAR-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="WAGNER_comorquestra_1001" position={[3.704, -0.993, -6.205]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="Cube" position={[-489.464, -298.582, 1564.252]} rotation={[-1.57, 0, 0]} scale={[19.35, 4.588, 1.469]}>
            <mesh name="Scene003" geometry={nodes.Scene003.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_1" geometry={nodes.Scene003_1.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_2" geometry={nodes.Scene003_2.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_3" geometry={nodes.Scene003_3.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_4" geometry={nodes.Scene003_4.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_5" geometry={nodes.Scene003_5.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_6" geometry={nodes.Scene003_6.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_7" geometry={nodes.Scene003_7.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_8" geometry={nodes.Scene003_8.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_9" geometry={nodes.Scene003_9.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_10" geometry={nodes.Scene003_10.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_11" geometry={nodes.Scene003_11.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_12" geometry={nodes.Scene003_12.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_13" geometry={nodes.Scene003_13.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_14" geometry={nodes.Scene003_14.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_15" geometry={nodes.Scene003_15.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_16" geometry={nodes.Scene003_16.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_17" geometry={nodes.Scene003_17.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_18" geometry={nodes.Scene003_18.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_19" geometry={nodes.Scene003_19.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_20" geometry={nodes.Scene003_20.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_21" geometry={nodes.Scene003_21.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_22" geometry={nodes.Scene003_22.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_23" geometry={nodes.Scene003_23.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_24" geometry={nodes.Scene003_24.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_25" geometry={nodes.Scene003_25.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_26" geometry={nodes.Scene003_26.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_27" geometry={nodes.Scene003_27.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_28" geometry={nodes.Scene003_28.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_29" geometry={nodes.Scene003_29.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_30" geometry={nodes.Scene003_30.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_31" geometry={nodes.Scene003_31.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_32" geometry={nodes.Scene003_32.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_33" geometry={nodes.Scene003_33.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_34" geometry={nodes.Scene003_34.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_35" geometry={nodes.Scene003_35.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_36" geometry={nodes.Scene003_36.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_37" geometry={nodes.Scene003_37.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_38" geometry={nodes.Scene003_38.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_39" geometry={nodes.Scene003_39.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_40" geometry={nodes.Scene003_40.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_41" geometry={nodes.Scene003_41.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_42" geometry={nodes.Scene003_42.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_43" geometry={nodes.Scene003_43.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_44" geometry={nodes.Scene003_44.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_45" geometry={nodes.Scene003_45.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_46" geometry={nodes.Scene003_46.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_47" geometry={nodes.Scene003_47.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Scene003_48" geometry={nodes.Scene003_48.geometry} material={materials.PaletteMaterial001} />
          </group>
        </group>
        <mesh name="Cube_005" geometry={nodes.Cube_005.geometry} material={materials.PaletteMaterial001} position={[-0.396, 0.607, 0.495]} scale={[0.007, 0.085, 0.085]} />
      </group>
    </group>
  )
}

useGLTF.preload('/wagnerAR-transformed.glb')
